---

sudo: false
dist: bionic
language: ruby
cache: bundler
addons:
  apt:
    packages:
    - tesseract-ocr
    - tesseract-ocr-eng

rvm:
  - 2.4.2
  - 2.5.3
before_install: gem install bundler -v 1.17.1
